webtalk_init -webtalk_dir D:/hellightning/Documents/CS-2022-Hardware/flow-fish-cpu/flowfish_cpu.sim/sim_1/behav/xsim/xsim.dir/openmips_min_spoc_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Aug 30 20:33:24 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6e24c5ad-a1d6-45c6-9e03-406dd9ededf9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9d1fc59a27024c2a8a6c386b10da21d5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "112" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15132_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2835162315 -regid "" -xml D:/hellightning/Documents/CS-2022-Hardware/flow-fish-cpu/flowfish_cpu.sim/sim_1/behav/xsim/xsim.dir/openmips_min_spoc_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/hellightning/Documents/CS-2022-Hardware/flow-fish-cpu/flowfish_cpu.sim/sim_1/behav/xsim/xsim.dir/openmips_min_spoc_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/hellightning/Documents/CS-2022-Hardware/flow-fish-cpu/flowfish_cpu.sim/sim_1/behav/xsim/xsim.dir/openmips_min_spoc_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
