# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/blk_data_ram/blk_data_ram.xci
# IP: The module: 'blk_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/blk_data_ram/blk_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/blk_data_ram/blk_data_ram.xci
# IP: The module: 'blk_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/blk_data_ram/blk_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
