# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/CPU2BOARD.xdc

# IP: ip/ila/ila.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] -quiet

# IP: ip/led_0_1/led_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_0 || ORIG_REF_NAME==led_0} -quiet] -quiet
