# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.cache/wt [current_project]
set_property parent.project_path D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/data_ram
  d:/LR/FPGA/light_show_ip
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/blk_mem_gen_0/fib.coe
add_files D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/inst_rom/fib.coe
add_files D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/inst_rom/4_fib_add_test.data.coe
read_verilog D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/defines.vh
set_property is_global_include true [get_files D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/defines.vh]
read_verilog -library xil_defaultlib {
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/control.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/ex.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/ex_mem.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/flowfish.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/id.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/id_ex.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/if_id.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/mem.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/mem_wb.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/pc_reg.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/regfile.v
  D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/new/top.v
}
read_ip -quiet d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/ila/ila.xci
set_property used_in_synthesis false [get_files -all d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/ila/ila_ooc.xdc]

read_ip -quiet d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/led_0_1/led_0.xci

read_ip -quiet D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/inst_rom/inst_rom.xci
set_property used_in_implementation false [get_files -all d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/inst_rom/inst_rom_ooc.xdc]

read_ip -quiet D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/blk_data_ram/blk_data_ram.xci
set_property used_in_implementation false [get_files -all d:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/sources_1/ip/blk_data_ram/blk_data_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/constrs_1/new/CPU2BOARD.xdc
set_property used_in_implementation false [get_files D:/LR/FPGA/flow-fish-cpu/flowfish_cpu.srcs/constrs_1/new/CPU2BOARD.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
